tickers = [
    'ARKK', 'DIA', 'EEM', 'EWZ', 'IWM', 'QQQ', 'SPY', 'XLE', 'XLF', 'AAL', 
    'AAP', 'AAPL', 'ABBV', 'ABEV', 'ABNB', 'ABT', 'ACN', 'ACWI', 'ADBE', 
    'ADGO', 'ADI', 'ADP', 'ADS', 'AEG', 'AEM', 'AI', 'AIG', 'AKO.B', 'AKOBD', 
    'ALAB', 'AMAT', 'AMD', 'AMGN', 'AMX', 'AMZN', 'ANF', 'ARCO', 'ARM', 
    'ASML', 'ASR', 'ASTS', 'AVGO', 'AVY', 'AXIA', 'AXP', 'AZN', 'B', 'B.C', 
    'B.D', 'BA', 'BA.C', 'BABA', 'BAK', 'BB', 'BBAS3', 'BBV', 'BCS', 'BHP', 
    'BIDU', 'BIIB', 'BIOX', 'BITF', 'BK', 'BKNG', 'BKR', 'BMY', 'BNG', 'BP', 
    'BRKB', 'BSBR', 'C', 'C.D', 'CAAP', 'CAH', 'CAR', 'CAT', 'CCL', 'CDE', 
    'CEG', 'CL', 'COIN', 'COPX', 'COST', 'CRM', 'CRWV', 'CSCO', 'CVS', 'CVX', 
    'CX', 'DAL', 'DD', 'DE', 'DEO', 'DHR', 'DISN', 'DOCU', 'DOW', 'E', 'EA', 
    'EBAY', 'EFX', 'ELPC', 'EMBJ', 'EQNR', 'ERIC', 'ERJD', 'ETHA', 'ETSY', 
    'EWJ', 'F', 'FCX', 'FDX', 'FMX', 'FSLR', 'FXI', 'GE', 'GFI', 'GGB', 'GILD', 
    'GLD', 'GLOB', 'GLW', 'GM', 'GOGLD', 'GOOGL', 'GPRK', 'GRMN', 'GS', 'GSK', 
    'GT', 'HAL', 'HAPV3', 'HD', 'HDB', 'HL', 'HMC', 'HMY', 'HOG', 'HON', 'HOOD', 
    'HPQ', 'HSBC', 'HSY', 'HUT', 'HWM', 'IBIT', 'IBM', 'IEUR', 'IFF', 'IJH', 
    'INFY', 'ING', 'INTC', 'IP', 'IREN', 'ISRG', 'ITUB', 'IVE', 'IVW', 'JCI', 
    'JD', 'JMIA', 'JNJ', 'JOYY', 'JPM', 'KEP', 'KGC', 'KMB', 'KO', 'KOFM', 
    'LAC', 'LAR', 'LLY', 'LMT', 'LND', 'LRCX', 'LREN3', 'LVS', 'LYG', 'MA', 
    'MCD', 'MDLZ', 'MDT', 'MELI', 'META', 'MFG', 'MGLU3', 'MMM', 'MO', 'MOS', 
    'MRK', 'MRNA', 'MRSH', 'MRVL', 'MSFT', 'MSI', 'MSTR', 'MU', 'MUFG', 'MUX', 
    'NEM', 'NFLX', 'NG', 'NGG', 'NIO', 'NKE', 'NOKA', 'NTES', 'NU', 'NUE', 
    'NVDA', 'NVS', 'NXE', 'ORCL', 'ORLY', 'OXY', 'PAAS', 'PAC', 'PAGS', 'PANW', 
    'PATH', 'PBI', 'PBR', 'PCAR', 'PDD', 'PEP', 'PETR3', 'PFE', 'PG', 'PHG', 
    'PINS', 'PKS', 'PLTR', 'PM', 'PRIO3', 'PSQ', 'PSX', 'PYPL', 'QCOM', 'RACE', 
    'RBLX', 'RENT3', 'RGTI', 'RIO', 'RIOT', 'RKLB', 'ROKU', 'ROST', 'RTX', 
    'SAN', 'SAP', 'SATL', 'SBS', 'SBUX', 'SCCO', 'SCHW', 'SDA', 'SE', 'SH', 
    'SHEL', 'SHOP', 'SID', 'SLB', 'SLV', 'SMH', 'SMSN', 'SNA', 'SNAP', 'SNOW', 
    'SONY', 'SPCE', 'SPGI', 'SPOT', 'STLA', 'STNE', 'SUZ', 'SWKS', 'SYY', 'T', 
    'TCOM', 'TEAM', 'TEN', 'TGT', 'TIMB', 'TJX', 'TM', 'TMO', 'TMUS', 'TQQQ', 
    'TRIP', 'TRVV', 'TSLA', 'TSM', 'TTE', 'TV', 'TWLO', 'TXN', 'TXR', 'UAL', 
    'UBER', 'UGP', 'UL', 'UNH', 'UNP', 'UPST', 'URA', 'URBN', 'USB', 'V', 
    'VALE', 'VEA', 'VIG', 'VIST', 'VIV', 'VOD', 'VRSN', 'VST', 'VXX', 'VZ', 
    'WBO', 'WFC', 'WMT', 'XLB', 'XLC', 'XLP', 'XLRE', 'XLU', 'XLV', 'XOM', 
    'XP', 'XROX', 'XYZ', 'YELP', 'YZCA', 'ZM'
]

print(f"Total: {len(tickers)} tickers")

